# Numpy

###### Actually, we rarely use the "math" library in deep learning because the inputs of the functions are real numbers. In deep learning we mostly use matrices and vectors. This is why numpy is more useful. 

In [49]:
import numpy as np

# Create an 1d array from a list
list1 = [0,1,2,3,4]
arr1d = np.array(list1)

print(type(arr1d))


<class 'numpy.ndarray'>


In [50]:
arr1d

array([0, 1, 2, 3, 4])

In [51]:
list1 + 2  

TypeError: can only concatenate list (not "int") to list

In [52]:
arr1d+2

array([2, 3, 4, 5, 6])

In [53]:
# Create a 2d array from a list of lists
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr2d_f = np.array(list2, dtype='float')

arr2d_f

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [55]:
# Convert to 'int' datatype
arr2d_f.astype('int')

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
arr2d_f.astype('str')

array([['0.0', '1.0', '2.0'],
       ['3.0', '4.0', '5.0'],
       ['6.0', '7.0', '8.0']],
      dtype='<U32')

In [57]:
# Create a boolean array
arr2d_b = np.array([1, 0, 10], dtype='bool')
arr2d_b

array([ True, False,  True], dtype=bool)

In [58]:
# Create an object array to hold numbers as well as strings
arr1d_obj = np.array([1, 'a',2,'b'], dtype='object')
arr1d_obj

array([1, 'a', 2, 'b'], dtype=object)

In [59]:
# Convert an array back to a list
arr1d_obj.tolist()

[1, 'a', 2, 'b']

In [60]:
#properties of an array(dim,shape,datatype,size)

list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2



array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [61]:
print('Shape: ', arr2.shape)
print('Datatype: ', arr2.dtype)
print('Size: ', arr2.size)
print('Num Dimensions: ', arr2.ndim)

Shape:  (3, 4)
Datatype:  float64
Size:  12
Num Dimensions:  2


In [62]:
#Extracting specific items from an array
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [63]:
arr2[:2,:2]

array([[ 1.,  2.],
       [ 3.,  4.]])

In [64]:
arr2[0:2,1:3]

array([[ 2.,  3.],
       [ 4.,  5.]])

In [65]:
arr2[1:,2:]

array([[ 5.,  6.],
       [ 7.,  8.]])

In [66]:
#numpy arrays support boolean indexing.

arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [67]:
b = arr2 > 4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [68]:
arr2[b]

array([ 5.,  6.,  5.,  6.,  7.,  8.])

In [69]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8],[9,10,11,12]]
arr2 = np.array(list2, dtype='float')
arr2

array([[  1.,   2.,   3.,   4.],
       [  3.,   4.,   5.,   6.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])

In [70]:
# Reverse only the row positions
arr2[::-1]

array([[  9.,  10.,  11.,  12.],
       [  5.,   6.,   7.,   8.],
       [  3.,   4.,   5.,   6.],
       [  1.,   2.,   3.,   4.]])

In [71]:
# Reverse both row and column positions
arr2[::-1,::-1]

array([[ 12.,  11.,  10.,   9.],
       [  8.,   7.,   6.,   5.],
       [  6.,   5.,   4.,   3.],
       [  4.,   3.,   2.,   1.]])

In [72]:
arr2[::-1,::]

array([[  9.,  10.,  11.,  12.],
       [  5.,   6.,   7.,   8.],
       [  3.,   4.,   5.,   6.],
       [  1.,   2.,   3.,   4.]])

In [73]:
arr2[::,::-1]

array([[  4.,   3.,   2.,   1.],
       [  6.,   5.,   4.,   3.],
       [  8.,   7.,   6.,   5.],
       [ 12.,  11.,  10.,   9.]])

In [74]:
# Insert a nan and an inf
arr2[1,1] = np.nan  # not a number
arr2[2,3] = np.inf  # infinite
arr2

array([[  1.,   2.,   3.,   4.],
       [  3.,  nan,   5.,   6.],
       [  5.,   6.,   7.,  inf],
       [  9.,  10.,  11.,  12.]])

In [75]:
# Replace nan and inf with -1

missing_bool = np.isnan(arr2) | np.isinf(arr2)
arr2[missing_bool] = -1  
arr2

array([[  1.,   2.,   3.,   4.],
       [  3.,  -1.,   5.,   6.],
       [  5.,   6.,   7.,  -1.],
       [  9.,  10.,  11.,  12.]])

In [76]:
#compute mean, min, max on the ndarray

print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  5.125
Max value is:  12.0
Min value is:  -1.0


In [77]:
# Row wise and column wise min

print("Column wise minimum: ", np.amin(arr2, axis=0))

print("Rowise minimum: ", np.amin(arr2, axis=1))

arr2

Column wise minimum:  [ 1. -1.  3. -1.]
Rowise minimum:  [ 1. -1. -1.  9.]


array([[  1.,   2.,   3.,   4.],
       [  3.,  -1.,   5.,   6.],
       [  5.,   6.,   7.,  -1.],
       [  9.,  10.,  11.,  12.]])

In [78]:
# Cumulative Sum
np.cumsum(arr2)

array([  1.,   3.,   6.,  10.,  13.,  12.,  17.,  23.,  28.,  34.,  41.,
        40.,  49.,  59.,  70.,  82.])

In [79]:
# Assign portion of arr2 to arr2a

arr2a = arr2[:2,:2]  

arr2a

array([[ 1.,  2.],
       [ 3., -1.]])

In [80]:
arr2a[:1, :1] = 100  

arr2a

array([[ 100.,    2.],
       [   3.,   -1.]])

In [81]:
arr2

array([[ 100.,    2.,    3.,    4.],
       [   3.,   -1.,    5.,    6.],
       [   5.,    6.,    7.,   -1.],
       [   9.,   10.,   11.,   12.]])

In [82]:
# Copy portion of arr2 to arr2b
arr2b = arr2[:2, :2].copy()

In [83]:
arr2b

array([[ 100.,    2.],
       [   3.,   -1.]])

In [84]:
arr2b[:1, :1] = 101
arr2b

array([[ 101.,    2.],
       [   3.,   -1.]])

In [85]:
arr2

array([[ 100.,    2.,    3.,    4.],
       [   3.,   -1.,    5.,    6.],
       [   5.,    6.,    7.,   -1.],
       [   9.,   10.,   11.,   12.]])

In [86]:
# Flatten it to a 1d array
arr2.flatten()

array([ 100.,    2.,    3.,    4.,    3.,   -1.,    5.,    6.,    5.,
          6.,    7.,   -1.,    9.,   10.,   11.,   12.])

In [87]:
b1 = arr2.flatten()  
b1[0] = 101  # changing b1 does not affect arr2

In [88]:
b1

array([ 101.,    2.,    3.,    4.,    3.,   -1.,    5.,    6.,    5.,
          6.,    7.,   -1.,    9.,   10.,   11.,   12.])

In [89]:
b2 = arr2.ravel()  
b2[0] = 101  # changing b2 changes arr2 also

In [90]:
b2

array([ 101.,    2.,    3.,    4.,    3.,   -1.,    5.,    6.,    5.,
          6.,    7.,   -1.,    9.,   10.,   11.,   12.])

In [91]:
#create sequences

print(np.arange(5))  
print(np.arange(0, 10))  
print(np.arange(0, 10, 2))  
print(np.arange(10, 0, -1))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]


In [92]:
#repeating sequences

a = [1,2,3] 
print('Tile:   ', np.tile(a, 2))
print('Repeat: ', np.repeat(a, 2))

Tile:    [1 2 3 1 2 3]
Repeat:  [1 1 2 2 3 3]


In [93]:
#get the unique items and the counts

np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [94]:
# Get the unique items and their counts

uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [0 2 3 4 5 7 8]
Counts       :  [1 2 1 1 1 2 2]


In [95]:
#get index locations using np.where

arr_rand = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print("Array: ", arr_rand)

index_gt5 = np.where(arr_rand > 5)
print("Positions where value > 5: ", index_gt5)

Array:  [8 8 3 7 7 0 4 2 5 2]
Positions where value > 5:  (array([0, 1, 3, 4]),)


In [96]:
# Take items at given index

arr_rand.take(index_gt5)

array([[8, 8, 7, 7]])

In [97]:
#import and export data as a csv file

#import using np.genfromtext   
#handle missing values,multiple delimiters,irregular no of columns

#less versatile np.loadtxt assumes dataset has no missing values

# Turn off scientific notation
np.set_printoptions(suppress=True)  

path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'

data = np.genfromtxt(path, delimiter=',',skip_header=1, filling_values=-999, dtype='float')

data[:3]  

array([[   18. ,     8. ,   307. ,   130. ,  3504. ,    12. ,    70. ,
            1. ,  -999. ],
       [   15. ,     8. ,   350. ,   165. ,  3693. ,    11.5,    70. ,
            1. ,  -999. ],
       [   18. ,     8. ,   318. ,   150. ,  3436. ,    11. ,    70. ,
            1. ,  -999. ]])

In [98]:
data[:2,:2]

array([[ 18.,   8.],
       [ 15.,   8.]])

In [99]:
#datasets with both numbers and characters

data2 = np.genfromtxt(path, delimiter=',',skip_header=1,dtype=None)

data2[:3]

array([( 18., 8,  307., 130, 3504,  12. , 70, 1, b'"chevrolet chevelle malibu"'),
       ( 15., 8,  350., 165, 3693,  11.5, 70, 1, b'"buick skylark 320"'),
       ( 18., 8,  318., 150, 3436,  11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i8'), ('f2', '<f8'), ('f3', '<i8'), ('f4', '<i8'), ('f5', '<f8'), ('f6', '<i8'), ('f7', '<i8'), ('f8', 'S38')])

In [100]:
# Save the array as a csv file

np.savetxt("out1.csv", data, delimiter=",")

In [101]:
#save and load numpy objects

list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [102]:
np.save('myarray.npy', arr2)  

In [103]:
#load it back

# Load a .npy file
a = np.load('myarray.npy')
print(a)

[[ 1.  2.  3.  4.]
 [ 3.  4.  5.  6.]
 [ 5.  6.  7.  8.]]


In [104]:
arr2a

array([[ 101.,    2.],
       [   3.,   -1.]])

In [105]:
arr2b

array([[ 101.,    2.],
       [   3.,   -1.]])

In [106]:
# Save multile numy arrays as a .npz file
np.savez('array.npz', arr2a, arr2b)


b = np.load('array.npz')

In [107]:
print(b.files)

['arr_0', 'arr_1']


In [108]:
b['arr_0']

array([[ 101.,    2.],
       [   3.,   -1.]])

In [109]:
b['arr_1']

array([[ 101.,    2.],
       [   3.,   -1.]])

In [110]:
#concatenate rowise and columnwise

a = np.zeros([4, 4])
b = np.ones([4, 4])

In [111]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [112]:
b

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [113]:
np.concatenate([a, b], axis=0)    

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [114]:
np.concatenate([a, b], axis=1)

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.]])

In [115]:
np.vstack([a,b])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [116]:
np.r_[a,b]

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [117]:
#horizontal concatenation

np.concatenate([a, b], axis=1)

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.]])

In [118]:
np.hstack([a,b])

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.]])

In [119]:
np.c_[a,b]

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.]])

In [120]:
#sort  columnwise and rowwise

arr = np.random.randint(1,6, size=[8, 4])

arr

array([[3, 3, 2, 1],
       [1, 5, 4, 5],
       [3, 1, 4, 2],
       [3, 4, 5, 5],
       [2, 4, 5, 5],
       [4, 4, 4, 2],
       [2, 4, 1, 3],
       [2, 2, 4, 3]])

In [121]:
np.sort(arr, axis=0)

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [2, 3, 4, 2],
       [2, 4, 4, 3],
       [3, 4, 4, 3],
       [3, 4, 4, 5],
       [3, 4, 5, 5],
       [4, 5, 5, 5]])

In [122]:
np.sort(arr, axis=1)

array([[1, 2, 3, 3],
       [1, 4, 5, 5],
       [1, 2, 3, 4],
       [3, 4, 5, 5],
       [2, 4, 5, 5],
       [2, 4, 4, 4],
       [1, 2, 3, 4],
       [2, 2, 3, 4]])

In [123]:
#sorting

lst3=[3,9,6,7,2,1,8]


x=np.array(lst3)

x

array([3, 9, 6, 7, 2, 1, 8])

In [124]:
sort_index=np.argsort(x)

sort_index

array([5, 4, 0, 2, 3, 6, 1])

In [125]:
x[sort_index]

array([1, 2, 3, 6, 7, 8, 9])

In [126]:
#sort based on one column 

arr


array([[3, 3, 2, 1],
       [1, 5, 4, 5],
       [3, 1, 4, 2],
       [3, 4, 5, 5],
       [2, 4, 5, 5],
       [4, 4, 4, 2],
       [2, 4, 1, 3],
       [2, 2, 4, 3]])

In [127]:
sort_index_1stCol=np.argsort(arr[:,0])

sort_index_1stCol

array([1, 4, 6, 7, 0, 2, 3, 5])

In [128]:
arr[sort_index_1stCol]

array([[1, 5, 4, 5],
       [2, 4, 5, 5],
       [2, 4, 1, 3],
       [2, 2, 4, 3],
       [3, 3, 2, 1],
       [3, 1, 4, 2],
       [3, 4, 5, 5],
       [4, 4, 4, 2]])

In [129]:
# Descending sort
arr[sort_index_1stCol[::-1]]

array([[4, 4, 4, 2],
       [3, 4, 5, 5],
       [3, 1, 4, 2],
       [3, 3, 2, 1],
       [2, 2, 4, 3],
       [2, 4, 1, 3],
       [2, 4, 5, 5],
       [1, 5, 4, 5]])

In [130]:
x=list('abcgkdgcdfj')

x

['a', 'b', 'c', 'g', 'k', 'd', 'g', 'c', 'd', 'f', 'j']

In [131]:
date64= np.datetime64('2018-02-03 23:10:10')
                     

date64

numpy.datetime64('2018-02-03T23:10:10')

In [132]:
dt64 = np.datetime64(date64, 'D')

dt64

numpy.datetime64('2018-02-03')

In [133]:
print('after 10 days',dt64+10)

tenminutes = np.timedelta64(10, 'm')  # 10 minutes
tenseconds = np.timedelta64(10, 's')  # 10 seconds
tennanoseconds = np.timedelta64(10, 'ns')  # 10 nanoseconds

after 10 days 2018-02-13


In [134]:
print('add 10 minutes',dt64+tenminutes)

print('add 10 nanaseconds',dt64+tennanoseconds)

add 10 minutes 2018-02-03T00:10
add 10 nanaseconds 2018-02-03T00:00:00.000000010


In [135]:
np.datetime_as_string(dt64)

dt64

print('Date: ', dt64)
print('is it bus day',np.is_busday(dt64))

print("Add 2 business days, rolling forward to nearest biz day: ", np.busday_offset(dt64, 2, roll='forward'))  

print("Add 2 business days, rolling backward to nearest biz day: ", np.busday_offset(dt64, 2, roll='backward')) 

Date:  2018-02-03
is it bus day False
Add 2 business days, rolling forward to nearest biz day:  2018-02-07
Add 2 business days, rolling backward to nearest biz day:  2018-02-06


In [136]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-10'))

dates

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08', '2018-02-09'], dtype='datetime64[D]')

In [137]:
np.is_busday(dates)

array([ True,  True, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [138]:
dt = dt64.tolist()

dt

print(dt)

2018-02-03


In [139]:
import datetime

print('Year: ', dt.year)  

print('Day of month: ', dt.day)

print('Month of year: ', dt.month)  

print('Day of Week: ', dt.weekday())

Year:  2018
Day of month:  3
Month of year:  2
Day of Week:  5


In [140]:
def foo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
print('x = 10 returns ', foo(10))
print('x = 11 returns ', foo(11))
print('x = [10, 11, 12] returns ', foo([10, 11, 12]))

x = 10 returns  5.0
x = 11 returns  121


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [141]:
foo_v = np.vectorize(foo, otypes=[float])

print('x = [10, 11, 12] returns ', foo_v([10, 11, 12]))

print('x = [[10, 11, 12], [1, 2, 3]] returns ', foo_v([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] returns  [   5.  121.    6.]
x = [[10, 11, 12], [1, 2, 3]] returns  [[   5.  121.    6.]
 [   1.    1.    9.]]


In [142]:
foo_p = np.vectorize(foo, otypes=[int])

print('x = [10, 11, 12] returns ', foo_p([10, 11, 12]))

x = [10, 11, 12] returns  [  5 121   6]


In [143]:
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [144]:
def max_minus_min(x):
    return np.max(x) - np.min(x)

print('Row wise: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

print('Column wise: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Row wise:  [8 8 6 8]
Column wise:  [7 8 2 7 6 5 8 5 5 5]


In [145]:
def max_min(x):
    print(np.max(x))
    print(np.min(x))

print('Row wise: ', np.apply_along_axis(max_min, 1, arr=arr_x))

print('Row wise: ', np.apply_along_axis(max_min, 0, arr=arr_x))

9
1
9
1
8
2
9
1
Row wise:  [None None None None]
9
2
9
1
4
2
8
1
9
3
6
1
9
1
7
2
6
1
8
3
Row wise:  [None None None None None None None None None None]


In [146]:
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
print('Where should 5 be inserted?: ', np.searchsorted(x, 5))

print('Where should 5 be inserted (right)?: ', np.searchsorted(x, 5, side='right'))

print('Where should 10 be inserted?: ', np.searchsorted(x, 10))

print('Where should 12 be inserted?: ', np.searchsorted(x, 12))

Where should 5 be inserted?:  5
Where should 5 be inserted (right)?:  6
Where should 10 be inserted?:  10
Where should 12 be inserted?:  10


In [148]:
x = np.arange(6)
print('Original array: ', x)

Original array:  [0 1 2 3 4 5]


In [149]:
x_col = x[:, np.newaxis]
print('x_col shape: ', x_col.shape)
print(x_col)

x_col shape:  (6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [150]:
x_row = x[np.newaxis, :]
print('x_row shape: ', x_row.shape)
print(x_row)

x_row shape:  (1, 6)
[[0 1 2 3 4 5]]


In [151]:
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
#For keeping the min and max range of dataset
np.clip(x, 3, 8)

array([3, 3, 3, 3, 4, 5, 6, 7, 8, 8])